THE NEXT WEB CLONE
Nkuria/TNW-clone pull request #3
Opened 2020-08-31 12:48 UTC by Nkuria

This a clone of the next web website homepage which demonstrates working knowledge of responsive web design using HTML and CSS.

2020-08-31 14:37 UTC, bertil291utn commented
# **Status:** Invalid 🚫

## Hey guys I hope you're having a great time

I see all your effort work on this project however I have to invalid due to: 

 - Please add a professional README file, follow this [template](https://github.com/microverseinc/readme-template)
  - [ ] Add a screenshot
  - [ ] Use markdown syntax for links
  Example:

  ```markdown
 [my-text-link](https://mylink)
  ```
  - [ ] Add more sections, check the template 

- Add a professional pullr request message, edit your pull request message, follow this [guideline](https://cdn.filestackcontent.com/osvFJEkQHWQsgDe0PJoQ)

### Summary
- Add a pull request following the guideline
- Update your README file

**Note:** to achieve all this check the link that is above this 
<hr>

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-08-31 16:41 UTC, bertil291utn requested changes
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish as the actual page, you required to do these changes, listed below:
- [ ] Instead `my-text-link` add some meaningful text like `[Linkedin](https://mylinedinlink)`, "my-text-link" only was an example. 
- [ ] Please medium screen approach.
  - Remember breakpoints for responsive design are 
    - Large 1024px up
    - Medium 768px up
     
   

| ACTUAL WEB PAGE | YOURS |
| :-------------: | :---: |
| ![image](https://user-images.githubusercontent.com/24902525/91743548-9915bf00-eb7d-11ea-8b28-a85d207e687c.png) | ![image](https://user-images.githubusercontent.com/24902525/91743517-90bd8400-eb7d-11ea-944d-4a79514b4e55.png) |

| Section/Screen                             | Large(1024px) | Medium(768px) | Small |
| :----------------------------------------- | :---: | :----: | :---: |
| Navigation bar                             |    1   |        |    6, 7   |
| Top 3 articles section                     |   2    |        |       |
| Latest news section                        |    3   |        |       |
| Latest Funding section                     |       |        |       |
| Categories (Apps, Gear, Tech, etc) section |       |        |       |
| Latest deals section                       |  4     |        |       |
| Footer                                     |  5     |        |  8,9     |
###### This table is given each section with his screen width approach, each issue is given by number below this table

(1) Remove TNW logo, for a large screen, is not right 
| ACTUAL WEB PAGE | YOURS |
| :-------------: | :---: |
| ![image](https://user-images.githubusercontent.com/24902525/91741236-0cb5cd00-eb7a-11ea-89fa-9021eb698600.png) | ![image](https://user-images.githubusercontent.com/24902525/91741188-f871d000-eb79-11ea-8780-88c8371261cd.png) |
(2) Add a padding to display properly this section
![image](https://user-images.githubusercontent.com/24902525/91741141-e42dd300-eb79-11ea-92b7-9cf4a243ca24.png)

(3) In this section from in large screens we have 4 rows, please another one 
![image](https://user-images.githubusercontent.com/24902525/91741388-4090f280-eb7a-11ea-8bd6-03f862460a62.png)

(4) In this section from in large screens we have 4 rows, please another one 
![image](https://user-images.githubusercontent.com/24902525/91741464-5f8f8480-eb7a-11ea-9cfc-515315ed5566.png)

(5) Fix the icon background should the\e same as the original page 

| ACTUAL WEB PAGE | YOURS |
| :-------------: | :---: |
| ![image](https://user-images.githubusercontent.com/24902525/91741747-c57c0c00-eb7a-11ea-8ede-bc8b0df35ba5.png) | ![image](https://user-images.githubusercontent.com/24902525/91741529-7afa8f80-eb7a-11ea-8f3d-64d62cd442b7.png) |

(6) Align the right icons section to the right.
(7) Add a less width to the logo

![image](https://user-images.githubusercontent.com/24902525/91743711-d9753d00-eb7d-11ea-96f0-8072e1bfe8ca.png)

(8) Align footer to the center
(9) Decrease font size
| ACTUAL WEB PAGE | YOURS |
| :-------------: | :---: |
| ![image](https://user-images.githubusercontent.com/24902525/91743863-1f320580-eb7e-11ea-961e-334ae6a1c1b9.png) | ![image](https://user-images.githubusercontent.com/24902525/91743833-0f1a2600-eb7e-11ea-9d71-eaa5826a8cbe.png) |

### Summary
- Add medium screen approach
-  Don't forget to work with inline comments below this comment box.

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-08-31 16:41 UTC, bertil291utn commented on style.css
> +  color: #f42;
## Using the Same Rule Repetitively[1]
- [ ] Create a class once and the use in each HTML tag where you need it.
- [ ] Delete all your ` color: #f42;` properties in entire CSS file
- [ ] Add your HTML tags

**Example:**

**CSS file**

```CSS
.color-orange{
   color: #f42;
}
```
**Html file**

```HTML
<div class="color-orange">
```
**Note:** Do this change to all properties in this file 

<hr>

_[1] [Good and bad  CSS practices](https://speckyboy.com/good-bad-css-practices/)_

2020-08-31 16:41 UTC, bertil291utn commented on style.css
> +  margin-top: 5%;
## Using the Same Rule Repetitively[1]
- [ ] Create a class once and the use in each HTML tag where you need it.
- [ ] Delete all your ` color: #f42;` properties in entire CSS file
- [ ] Add your HTML tags

**Example:**

**CSS file**

```CSS
.color-orange{
   color: #f42;
}
```
**Html file**

```HTML
<div class="color-orange">
```
**Note:** Do this change to all properties in this file 

<hr>

_[1] [Good and bad  CSS practices](https://speckyboy.com/good-bad-css-practices/)_

2020-08-31 16:41 UTC, bertil291utn commented on style.css
> +}
## Using the Same Rule Repetitively[1]
- [ ] Create a class once and the use in each HTML tag where you need it.
- [ ] Delete all your ` color: #f42;` properties in entire CSS file
- [ ] Add your HTML tags

**Example:**

**CSS file**

```CSS
.color-orange{
   color: #f42;
}
```
**Html file**

```HTML
<div class="color-orange">
```
**Note:** Do this change to all properties in this file 

<hr>

_[1] [Good and bad  CSS practices](https://speckyboy.com/good-bad-css-practices/)_

2020-09-01 11:31 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

Hey team :+1: 

You did a great job here, and we are almost there. This is a hard one, so please exercise patience. Your work has been great so far :ok_hand: 

I believe some new bugs came out after the last review, so please address them (I marked them in the inline comments below). 

There is one important detail that should have been mentioned before, but it was not (we are sorry about that). Because of this, I will mark as optional (but it would be great if you do it):

**optiona**l =>  As the requirements in pathwright state, you should use the mobile-first approach, that means that the default is the small screen and no media queries are used for this size, next you should state the media queries for tablet @media screen and (min-width: 768px) and lastly the media queries for desktop @media screen and (min-width: 1024px). [You did desktop-first and established max-widths for your media queries].


### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-09-01 11:31 UTC, expjazz commented on index.html
> +                    GET TICKETS
####  Large Screen Size

- [ ]  Delete this whitespace between the navbar and the Jumbotron

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/91842262-21519e00-ec2a-11ea-8c92-a6b0b13312b3.png) | ![image](https://user-images.githubusercontent.com/61479648/91842297-31697d80-ec2a-11ea-80b4-301822e25fe9.png) |

#### Medium Screen Size and Mobile Screen SIze

- [ ] The big TNW from the news articles should not show up 

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/91842540-a2109a00-ec2a-11ea-8624-665b84389d98.png) |![image](https://user-images.githubusercontent.com/61479648/91842598-b6ed2d80-ec2a-11ea-8e05-42ec679d2a4e.png) |

2020-09-01 11:31 UTC, expjazz commented on index.html
> +                <a href="#">Events</a>
#### Medium Screen Size

- [ ] The fonts in the middle nav are too different (they need to be bigger and centralized in the y-axis)

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/91842723-eef47080-ec2a-11ea-9e83-0792821ee180.png)|![image](https://user-images.githubusercontent.com/61479648/91842781-03d10400-ec2b-11ea-8782-29ae2bf04f54.png) |

#### Mobile Screen Size

- [ ] The height of the layers is too different (the gray needs to be smaller and the yellow bigger)

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/91842919-42ff5500-ec2b-11ea-93d0-256d292b8d9d.png) | ![image](https://user-images.githubusercontent.com/61479648/91842946-4bf02680-ec2b-11ea-8ba1-a4029395c985.png) |

- [ ] The layout breaks below 450px 

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/91843090-835ed300-ec2b-11ea-8967-700c5cf09403.png) |![image](https://user-images.githubusercontent.com/61479648/91843123-92de1c00-ec2b-11ea-8568-999588fcc7b3.png)  |

2020-09-01 11:31 UTC, expjazz commented on index.html
> +    </footer>
#### All screen sizes

- [ ] The icons are broken now.

![image](https://user-images.githubusercontent.com/61479648/91843389-11d35480-ec2c-11ea-8024-a759a7d80ba3.png)

#### Mobile Screen Size

- [ ] The bottom part should have smaller fonts

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/91843493-33344080-ec2c-11ea-8992-434892a4c2c5.png)| ![image](https://user-images.githubusercontent.com/61479648/91843520-40e9c600-ec2c-11ea-9b07-dcf236cfc6b2.png) |

2020-09-01 16:36 UTC, MuriloRoque requested changes
# Status: Changes requested :red_circle: 

### Hello @Nkuria and @Lidya1234 :wave: 

### Thank you for making the required changes made by the last TSE, but I believe there was a misunderstanding when he told you about the logo on medium screens:

- [x] Fix the logo, check the original, the right one to vanish is **not** in the navbar, it's in the **main** content (BIG article in the first row).

***YOURS:***

![Screenshot from 2020-09-01 13-29-06](https://user-images.githubusercontent.com/59691171/91881368-c767cd00-ec57-11ea-8b93-0c8f83accafc.png)

***ORIGINAL***

![Screenshot from 2020-09-01 13-31-02](https://user-images.githubusercontent.com/59691171/91881395-cf277180-ec57-11ea-9023-0cc9a77ab078.png)


## Kindly make the requested changes and submit for another review, please :pray: 

## I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-09-02 14:08 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Dami Oduronbi** 
Good job with the improvements for this project :muscle:  :muscle:
There are more details to improve before you can go ahead:
- [ ] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition.
- [ ]  Check the footer of your page, in small screen size, change it to match with the original:

| Yours | Original |
|:---:|:---:|
|![image](https://i.imgur.com/Pgk6HXZl.png) | ![image](https://i.imgur.com/jD9CAmll.png) |

- [ ] the height of the images in the first section doesn't match the original one. Besides, change the color of the menu icon:

| Yours | Original |
|:---:|:---:|
|![image](https://i.imgur.com/7BsB3zNl.png) | ![image](https://i.imgur.com/08PPWkMl.png) |

- [ ] The layout for the medium screen size should be like this:

- latest news: 3 columns
- latest funding: 3 columns
- categories section: 2 columns
- latest deals: 3 columns

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-09-02 14:08 UTC, andresporras3423 commented on style.css
> +  }
Group with selector on line 340

2020-09-03 08:29 UTC, kitpao requested changes
# 👋 Hello @Nkuria and @Lidya1234 

Great job making most of the fixes in your project 🌟 Your page is becoming more like the original 👍 
Please make the changes indicated below 🔽 in order for your project to be approved

**_Note:_** All the **[OPTIONAL]** are **not required** in order to approve your project but are personal suggestions to improve your coding experience

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-09-03 08:29 UTC, kitpao commented on style.css
> +  }
- [ ] **OPTIONAL** I see you have many classes with the same rule of `display: none;` because you are using different responsive behavior for each of the classes. But you can make it simpler for yourselves by adding "responsive classes"; when you get to the next project "bootstrap" please check out how they use them so you can have a better idea in your future projects :)

2020-09-03 08:29 UTC, kitpao commented on index.html
> +          <a href="#">contacts</a>
- [ ] **OPTIONAL** To make it look consistent, you can capitalize "Contacts", or make all of these elements uppercase as in the original

2020-09-03 08:29 UTC, kitpao commented on index.html
> +          StackPath</p>
- [ ] In your footer, it is a hard requirement to use the TNW logo: 
![image](https://user-images.githubusercontent.com/53256139/92088376-642e8580-ed92-11ea-8583-5d3d176452c8.png)

2020-09-03 08:29 UTC, kitpao commented on index.html
> +        />
- [ ] It is important that you know how to place your elements correctly, so please add the corresponding text to your images. ( **Hint:** I would suggest you that you use divs with position: relative to accommodate everything and use background-images for the pictures, then use text with position: absolute so it is easy for you to position it)
![image](https://user-images.githubusercontent.com/53256139/92088925-2847f000-ed93-11ea-8180-eb3e243f2b32.png)

2020-09-03 08:29 UTC, kitpao commented on index.html
> +        <img class="tnw2020-3" src="images/tnw2020-3.jpg" alt="pic here">
- [ ] **OPTIONAL** That tnw2020-3 image is not required, it is not showing in the original, you can take it out

2020-09-03 08:29 UTC, kitpao commented on index.html
> +      </div>
- [ ] Notice that you have the See more, Get updates, Add info links in the same row and in the original it is displaying below the title, please emulate the original. (This is an easy fix, you can use `flex-direction: column;` in the medium size of your .section-3-top flex to change the way they are positioned)
![image](https://user-images.githubusercontent.com/53256139/92090109-a5c03000-ed94-11ea-9b89-e593ea344e3e.png)

2020-09-03 08:29 UTC, kitpao commented on index.html
> +        ></a>
- [ ] Notice the color of your title is yellow and the original is orange. Please fix this

2020-09-03 14:58 UTC, kitpao requested changes
# 👋 Hi again Team

Great work fixing almost all of your missing details 🏅 You are almost there!

- [ ] Please implement the text (instead of screenshots) in your side images, the orange part with the prices, the sections Apps, Gear, Tech, Creative, etc and you will be done 

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-09-03 18:09 UTC, MuriloRoque requested changes
# Status: Changes requested :red_circle: 

### Hello again @Nkuria and @Lidya1234 :wave: 

- [ ]  According to the last review, I see that you fixed some of the images in one of the sections, but you are still missing some of them in the 'Latest Funding' section:

![Screenshot from 2020-09-03 15-05-54](https://user-images.githubusercontent.com/59691171/92151261-392a4d00-edf7-11ea-9528-f9a1f21433f1.png)
<br>
### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-09-03 19:14 UTC, MuriloRoque requested changes
# Status: Changes requested :red_circle: 

### Hello again @Nkuria and @Lidya1234 :wave: 

### Thank you for adding the texts, but they still need some fixing, check below:

- [ ] In large screens, the text is overlapping with the image:

![Screenshot from 2020-09-03 16-10-21](https://user-images.githubusercontent.com/59691171/92157097-51529a00-ee00-11ea-8759-a8b6ffabb688.png)

- [ ] In small and medium screens, the font size is too small:

![Screenshot from 2020-09-03 16-10-07](https://user-images.githubusercontent.com/59691171/92157125-5d3e5c00-ee00-11ea-8798-0208e10ff4a1.png)

***NOTE:*** Please, only request a review when you are sure you won't change anything else. I saw you pushing changes while I was doing my review, and my review could become inaccurate :pray: 

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-09-03 20:05 UTC, MuriloRoque approved these changes
# Status: Approved :green_circle: 

### Hello again @Nkuria and @Lidya1234 :wave: 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-09-04 11:37 UTC, merged